### ISSUE TITLE
Playback progress broken in 0.9.9

### ISSUE THREAD

**Issue by sparks-alec** [stagehacks/Cue-View#102]
**Describe the bug**
"playback progress" broken in 0.9.9. works in 0.9.6. I think just in QLab?

**To Reproduce**
https://twitter.com/rsmck/status/1663118833815617536

**Comment by jwetzell** [comment]
I've got playback and generally workspace loading or 4 fixed now. Just some checks in places for QLab version to parse the address differently and some null checks on properties that aren't always included in calls back from 4.
