### ISSUE TITLE
Add support for PosiStageNet Viewing

### ISSUE THREAD

**Issue by mylesie** [stagehacks/Cue-View#141]
Have you had any thought of adding a viewer for PosiStageNet Traffic.
https://posistage.net/
https://github.com/vyv

You would possibly have to specify which Tracker (Axis) you want to see, and maybe a scaling and Unit (mm, ft) etc.

Thanks

**Comment by jwetzell** [comment]
I will look into this. The protocol seems fairly well defined and they have an example server to test with. I'm not sure what an interface might look like but I think processing the data will be enough work for right now.

**Comment by jwetzell** [comment]
Got a basic implementation of the protocol up. 
![screenshot](https://github.com/stagehacks/Cue-View/assets/18341515/11a42efa-1ac6-437e-8515-b55424bd71d1)

Working on what a potential layout would be if you have any suggestions or examples. I tried finding some examples online but haven't had any luck.
