### ISSUE TITLE
Feature Request: Collapse/Hide Sidebar

### ISSUE THREAD

**Issue by rsmck** [stagehacks/Cue-View#185]
**Is your feature request related to a problem? Please describe.**
We run Cue View on the DSM's desk on a very small screen in a fixed environment (Qlab and Eos only), every pixel of width matters, so it would be good to be able to hide the sidebar column on the left via a menu bar option or keyboard shortcut. 

**Describe the solution you'd like**
Addition of a menu item "Hide Sidebar", the state of which is remembered when the app is closed/reopened.

**Comment by jwetzell** [comment]
I like that, quick test the only thing I can think that is going to need to be "solved" is the device name and nav buttons overlapping like this 
<img width="799" alt="Screenshot 2024-01-15 at 2 58 37 PM" src="https://github.com/stagehacks/Cue-View/assets/18341515/97cff598-74e0-48aa-9e81-d9fd73d767f0">

**Comment by jwetzell** [comment]
@rsmck sorry for the delay, this is now available in v1.1.0

**Comment by rsmck** [comment]
You have no need to apologise for a delay in implementing a niche feature request in a piece of software I don't pay for :D 

Many thanks! 

(FWIW and for anyone interested, this is why we wanted this :) https://rsmck.co.uk/blog/prompt-corner-display/)
