### ISSUE TITLE
Enhancement request - show progress of QLab cues

### ISSUE THREAD

**Issue by CSTECH-peterhodgkinson** [stagehacks/Cue-View#2]
hi,

When using Cue View for me (I might be doing something silly so if I am my apologies) Cue View doesn't appear to show the Pre Wait, Action or Post Wait progress on the cues.
However, this data is exposed via OSC which is I believe how Cue View communicates with QLab.

The OSC Commands available for this are:

/cue/{cue_number}/PreWaitElapsed
/cue/{cue_number}/ActionElapsed
/cue/{cue_number}/PostWaitElapsed

For these, the OSC Reply will look something like this:
{
    "status":"ok",
    "data":"90.1234",
    "workspace_id":"7ABC...",
    "address":"\/cue\/{cue_number}\/ActionElapsed"
}

The data field contains the number of seconds into the PreWait, Action or PostWait

There is also a number of OSC commands where the data field contains the percentage though, rather than the number of seconds, these are:

/cue/{cue_number}/percentPreWaitElapsed
/cue/{cue_number}/percentActionElapsed
/cue/{cue_number}/percentPostWaitElapsed

I was wondering if this would allow for enhancement of Cue View at some point - unless the feature is already implemented and I am managing to be a fool somehow?
I do see that Cue View shows me the fact that a cue is active and I can't see any mention of these OSC commands in the plugin javascript file.
Sadly, I don't believe that I am competent enough to add this functionality myself.

Kindest Regards

Peter Hodgkinson

**Comment by sparks-alec** [comment]
Working on it! Some changes need to happen on the backend to make it possible to update info on just one cue at a time. Currently Cue View draws the whole Cue List all over again every time anything changes, which would be bad when you're getting tens of updates per second from a cue.

**Comment by sparks-alec** [comment]
I think this issue is addressed in 0.9.5- let me know what you think!
