### ISSUE TITLE
ESLint and Prettier have been neglected

### ISSUE THREAD

**Issue by jwetzell** [stagehacks/Cue-View#27]
Looks like the ESLint and Prettier stuff hasn't been regularly run. Could enforce this on the main branch using GitHub Actions.
Could also do some automatic stuff using GitHub Actions like auto apply and commit formatting/linting (not all linting things can be auto fixed).

**Comment by jwetzell** [comment]
right now I ran eslint and prettier on everything and pushed it to the lint-n-pretty branch

**Comment by sparks-alec** [comment]
hmmm, it used to run automatically for me, not sure when I broke that. are there better tools for this?

**Comment by jwetzell** [comment]
I think eslint and prettier combo are good. I'm going to check in the .vscode folder with some settings and extension recommendations so that if you are using vs code it should do things on save (without you having to edit your own vscode settings)

**Comment by jwetzell** [comment]
.vscode settings for eslint and prettier were added in pr #29
