### ISSUE TITLE
QLab groups not setup right if multiple workspaces

### ISSUE THREAD

**Issue by jwetzell** [stagehacks/Cue-View#277]
If a single workspace is open the group modes are setup right and displayed correctly. If I open a 2nd workspace (even empty) on the same computer then no group modes seem to show up (cues are there just not represented in their groups properly).

**Comment by sparks-alec** [comment]
this line https://github.com/stagehacks/Cue-View/blob/a6bcac5adf0ffbd33c5b0c9540d53e871a02752c/plugins/qlab/main.js#L76 I introduced seems to be troublesome generally but especially when you have multiple workspaces. Commenting it out seems to make the problem go away.

I am not sure exactly what its purpose is but it does seem imprecise. I am testing with it commented out.

**Comment by sparks-alec** [comment]
I have commented out this line on main. This should be fixed in future releases.
