### ISSUE TITLE
Add support for Digico Consoles

### ISSUE THREAD

**Issue by jwetzell** [stagehacks/Cue-View#31]
Moving "future devices" to issues so that some discussion can take place if needed (look/feel ideas, libraries, control information, etc.).

**Comment by velocity23** [comment]
A useful (unofficial) reference for DiGiCo's OSC implementation is available here:
https://raw.githubusercontent.com/bitfocus/companion-module-digico-osc/master/api/DiGiCo_OTHER_OSC_List_17_11_14.pdf

**Comment by jwetzell** [comment]
A decent repository that might contain some useful stuff for the actual "getting information out of the console" side of things. https://bitbucket.org/yovio/digico-sd9 

That pdf looks pretty nice but is really only about control no information querying address formats.

**Comment by sparks-alec** [comment]
DiGiCo consoles have swappable OSC command lists (because of course they would) so I dumped the two lists off this SD11. They aren't plain text but if you run strings on them you get some fun stuff.
[Archive.zip](https://github.com/stagehacks/Cue-View/files/10505476/Archive.zip)

**Comment by sparks-alec** [comment]
and heck, for completion's sake, pulled the list off an SD10 too
[IPAD SD5-SD7-SD10.dosc.zip](https://github.com/stagehacks/Cue-View/files/10505765/IPAD.SD5-SD7-SD10.dosc.zip)
