### ISSUE TITLE
Add support for Shure Digital Wireless

### ISSUE THREAD

**Issue by jwetzell** [stagehacks/Cue-View#36]
The Shure digital wireless ULX-D, QLX-D, SLX-D all support control over TCP/IP (looks to be quite similar across the series). Even supports viewing meter levels.

**Comment by jwetzell** [comment]
[ULX-D TCP Docs](https://pubs.shure.com/command-strings/ULXD/en-US)

**Comment by sparks-alec** [comment]
currently looks like this, @jwetzell any thoughts?
- individual channel elements are floating so if you have lots of receivers they can all fit in a narrow pinned view
- I need to pretty up the color scheme of the bar graphs

![image](https://user-images.githubusercontent.com/919746/209979737-40194afe-a824-4ec8-9312-54ddfb6de4c2.png)

**Comment by jwetzell** [comment]
Looks pretty clean is the CH 1 CH 2 above each channel the name set in the unit? Maybe can look at Wireless Workbench for some color/design inspiration.

**Comment by sparks-alec** [comment]
Shure Wireless will be included in v1.0.
