### ISSUE TITLE
Art-Net Cleanup

### ISSUE THREAD

**Issue by sparks-alec** [stagehacks/Cue-View#37]
- Many situations where Art-Net is discovered on the network but can't be displayed for some reason
- More efficient view drawing

**Comment by jwetzell** [comment]
Fixed the config format to the new format which I think mostly fixes the first bullet, needs a bit more testing.

**Comment by jwetzell** [comment]
@sparks-alec I swapped out all calls to `.innerText = ` with `.textContent = ` as I read some stuff on how bad the performance of innerText was. This resulted in about 2x FPS with Artnet (29->60ish) and 4x with sACN (15ish->60ish). These are the only two plugins I found uses of `.innerText =` in but a good thing to note for future.

I would say this takes care of the 2nd bullet would love to see if you notice a difference in speed.

**Comment by jwetzell** [comment]
@sparks-alec can read some more about the differences [here](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext) under the _Differences from innerText_ section. Biggest factor is this part

> Moreover, since innerText takes CSS styles into account, reading the value of innerText triggers a [reflow](https://developer.mozilla.org/en-US/docs/Glossary/Reflow) to ensure up-to-date computed styles. (Reflows can be computationally expensive, and thus should be avoided when possible.)

**Comment by sparks-alec** [comment]
This is phenomenal!!!
