### ISSUE TITLE
Check config format across all plugins

### ISSUE THREAD

**Issue by jwetzell** [stagehacks/Cue-View#50]
There are some inconsistencies across plugins of the format for the config object. So I think a once over of all of them should be done to make sure things are nested/named properly. I just noticed the `mayChangePort` didn't line up in a couple of the plugins so think it's best to run through the config on everything. 

### Plugins
- [ ] artnet
- [x] eos
- [x] pjlink
- [x] qlab
- [x] sacn
- [x] shure
- [x] watchout
- [x] x32
- [x] xair

**Comment by jwetzell** [comment]
@sparks-alec Artnet still has a `mayChangePort` property under `searchOptions` that's not correct is it?

**Comment by sparks-alec** [comment]
fixed!
