### ISSUE TITLE
deviceDrawArea.onclick ?

### ISSUE THREAD

**Issue by jwetzell** [stagehacks/Cue-View#51]
what are these line in view.js doing? just debug? I'm trying to go through and clean up debug logging/commented out code and things like that and ran across this.

https://github.com/stagehacks/Cue-View/blob/5ccb3c0828037056887e0f99fbd6a96ee0b810c4/src/view.js#L23-L25

**Comment by sparks-alec** [comment]
oh oops that's debug, just removed it!
