### ISSUE TITLE
EOS no connection 

### ISSUE THREAD

**Issue by Jus17** [stagehacks/Cue-View#55]
Hi, I'm really interested to use your software with eos, but I cannot make it work. View cue find eos but it has a red cross near it. I've followed the instructions you provided on the selected window but the red cross doesn't disappear and connection is not possible.

Is it a bug? I'm trying to communicate with eos on my own PC

Thank you

**Comment by Jus17** [comment]
I'm using the latest beta (0.9.8.0).
In the show control section > OSC, I've set:
- enabled OSC RX and OSC TX
- OSC UDP RX Port 8000 (default)
- OSC UDP TX Port 8001 (default)
- all other settings are empty


On cue view the address is the same address seen on eos network.. but I've tried also with 127.0.0.1

**Comment by Jus17** [comment]
From the diagnostic tab (99) it seems that the output of OSC packet are sent on port 52537

**Comment by jwetzell** [comment]
The EOS plugin uses TCP. If you left the TCP port empty in EOS Software then the default port value of 3032 should be correct.

**Comment by Jus17** [comment]
Yes the TCP PORT is empty. I'm with the latest eos family software

**Comment by Jus17** [comment]
There are on the same computer

**Comment by Jus17** [comment]
Yes it's enabled

**Comment by jwetzell** [comment]
So under diagnostics screen do you see incoming osc there should be one every 5 seconds that says `[OSC Packet] /eos/ping`

**Comment by jwetzell** [comment]
Another thing it seems that it only updates the device as "online" if a cue list/cue exists. (which I might consider a bug)

**Comment by Jus17** [comment]
Diagnostic tells me that TCP Osc connection succeeded but nothing change in cue view

**Comment by jwetzell** [comment]
Do you have any cues recorded? It seems the status does not change for EOS unless it sees any cues/lists

**Comment by Jus17** [comment]
Yes I've one with two cues

**Comment by Jus17** [comment]
![Uploading 16740801342828631927107755631894.jpg…]()

**Comment by Jus17** [comment]
![16740802422232977946000143675222](https://user-images.githubusercontent.com/123023969/213307470-8b2f0146-c79e-41f1-b516-fbda498c473e.jpg)

**Comment by jwetzell** [comment]
Can you open up Cue View and select `View->Toggle Developer Tools`. When that opens could you select `Console` from the developer tools panel (item to the right of `Elements`) and see if there are any errors in that console that might help out as it looks like it is communicating.

**Comment by Jus17** [comment]
Mmm all seems started and no errors

**Comment by Jus17** [comment]
I really don't see this message in diagnostic: [OSC Packet] /eos/ping

**Comment by jwetzell** [comment]
Do you have `Incoming OSC` turned on in the diagnostics menu?
![Screenshot_20230118_163027](https://user-images.githubusercontent.com/18341515/213309311-b531adc7-be74-4faa-8463-d96a61d4a11b.png)

**Comment by Jus17** [comment]
Yes, it was the first thing I've checked.. is it maybe a problem that I've not a consolle linked to my pc?

**Comment by Jus17** [comment]
![16740815079146080444957959483481](https://user-images.githubusercontent.com/123023969/213310721-d758a9a0-49e9-457c-aab9-7cda3c0cbc93.jpg)


It seems that eos sends Osc packet

**Comment by jwetzell** [comment]
I'm testing with the EOS family software on my PC with v0.9.8 and have no issues after I enable OSC RX/TX. All those message in the log say UDP and Cue View does not use UDP to communicate with EOS so not sure what that is about.

**Comment by jwetzell** [comment]
How are you starting up the EOS from the shell? Which option are you selecting?

**Comment by Jus17** [comment]
I start it in offline mode. I've discovered that in network shell I have to select TCP format for OSC 1.1 (SLIP), in this way View cue works as it should. If I revert it to TCP format for OSC 1.0 (packet length headers) it doesn't work, giving me connection error.

**Comment by jwetzell** [comment]
Huh yeah my EOS was already default to that setting. But that is usually the standard format for OSC TCP

**Comment by jwetzell** [comment]
So with the SLIP option enabled everything works as it's supposed to @Jus17 ?

Looking at that setting I see that the `Third Party OSC` option is fixed to port 3037 which I vaguely remember thinking was a typo (port 3032 vs 3037). @sparks-alec might be able to confirm. Not sure I was aware of the `Third Party OSC` option which was forcing the port (3037) and format (SLIP)

**Comment by Jus17** [comment]
Yes with SLIP option everything works as it should, thank you!

Is it possible to implement also the cue view of Show Cue System? It's the only real alternative to Qlab for windows

Thank you again for this software!

**Comment by jwetzell** [comment]
Nice I will close those issue then. 

Our ability to add software to the list usually comes down to a couple things: the ability to communicate with a piece of software (and how well that is documented) and our ability to test (demo /free versions of software). If you would like to open another issue requests show cue systems we can add it to the list of things to look at!

**Comment by sparks-alec** [comment]
`Third Party OSC` was only introduced in Nov 2021 so it's still kind of a secret! And yes is a typo, 3032 is the default value for the regular non-Third-Party TCP port, so I had that wrong in this case.
