### ISSUE TITLE
Missing Add button

### ISSUE THREAD

**Issue by cmtk** [stagehacks/Cue-View#6]
When I launch Cue View 0.9.5-pre (Mac), the + icon is missing from the Add button, and the button is not functional (hovering or clicking produces no change). This is a brand new install.
![image](https://user-images.githubusercontent.com/12386329/162133869-e9ded3f7-1181-4de2-8483-057450d54a0e.png)

I do have a console error during plugin file loading:
```
/Applications/Cue View.app/Contents/Resources/app.asar/preload.js:13 init!
/Applications/Cue View.app/Contents/Resources/app.asar/src/plugins.js:12 Loading plugin files... /Applications/Cue View.app/Contents/Resources/app.asar/src/../plugins
/Applications/Cue View.app/Contents/Resources/app.asar/src/plugins.js:19 artnet started
/Applications/Cue View.app/Contents/Resources/app.asar/src/plugins.js:19 eos started
node:internal/fs/utils:342 Uncaught Error: ENOENT: no such file or directory, open './plugins/eos/cue.ejs'
```

**Comment by sparks-alec** [comment]
I believe 0.9.6 fixes this!

**Comment by cmtk** [comment]
It does indeed!
