### ISSUE TITLE
QLab Nested groups don't display properly

### ISSUE THREAD

**Issue by jwetzell** [stagehacks/Cue-View#9]
When a workspace has nested groups there seems to be a problem with the logic of when to display the bottom left corner (See attached image).
<img width="300" alt="Screen Shot 2022-11-19 at 10 37 04 AM" src="https://user-images.githubusercontent.com/18341515/202861665-bfa81e6e-b25f-478d-86e6-885fab025789.png">

**Comment by sparks-alec** [comment]
I will work on this! The group border logic is surprisingly complex.

**Comment by jwetzell** [comment]
Yeah, I didn't have the time to unravel it so I made the issue so I at least wouldn't forget to come back to it...
