### ISSUE TITLE
In EOS v3.2 Cue-View doesn't see EOS

### ISSUE THREAD

**Issue by aarblaster** [stagehacks/Cue-View#99]
**Describe the bug**
On upgrading EOS to V3.2 Cue-View stopped displaying cues.

**To Reproduce**
1. Upgrade EOS to v3.2.
2. Attempt to connect to known IP.
3. Ensure OSC TX/RX is enabled, Third Party OSC is enabled (now in settings not shell).
4. Refresh Cue-View or delete device and try again.

In all of the above circumstances, sACN can be viewed by Cue-View but not EOS cue lists.

**Expected behavior**
Expected Cue-View to display cues from EOS.

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version: v13.3.1 (22E772610a)
 and
- OS: Windows
- Version: v10

**Additional context**
Have tried multiple machines and multiple network arrangements. This could be (probably is) an ETC third party OSC bug.

**Comment by jwetzell** [comment]
Hmm. I just updated EOS to v3.2 on my test Windows machine and reset up the Show Controls settings (OSC TCP port, TX/RX Enabled) then added launched Cue-View and scanned (also added manually as a test) and everything loaded as usual.

**Comment by aarblaster** [comment]
Hmmm well that's interesting! Thanks for the quick reply too. I'll give it a go again tomorrow and see if I can work out what else has changed on the network.

**Comment by aarblaster** [comment]
I have set up on a new simplified system. ION running v3.2, into an unmanaged network switch, into a mac running cue view (and a windows 10 machine later just to check). And could not for the life of me get the EOS view to work. I can in all instances see sACN feed. I double triple checked that remotes were enabled, TCP OSC, 3rd party osc and osc tx/rx were all enabled. So I must be missing something. But for the life of me I can't figure it out. Sometimes noting happens and sometimes I get an error saying 'net::ERR_INTERNET_DISCONNECTED'. Except sACN still works and only ethernet is connected.

**Comment by sparks-alec** [comment]
I can replicate the problem. I get "eos is not responding to requests for data" when running 0.9.8. Works fine with fresh code off the main branch.

**Comment by aarblaster** [comment]
Thanks for the update @sparks-alec.  At least we can replicate the fault.

**Comment by sparks-alec** [comment]
Check release 0.9.9, it appears to resolve the issue for me.

**Comment by jwetzell** [comment]
Also might be interesting if you click Help->Check for Updates it should in theory find the new release and walk you through download/install. Can't say I've seen it tested outside of us locally, but should in theory work.

**Comment by aarblaster** [comment]
Success! 🥳 Both the new software and the auto update work. Cue View even offered to update for me automatically for me. Thanks for the help troubleshooting and the quick fix.
